### ISSUE TITLE
Blazor WASM support

### ISSUE THREAD

**Issue by voros1** [dxFeed/dxfeed-graal-net-api#33]
When running the example code in a Blazor WASM application, I encounter the following:
![image](https://github.com/dxFeed/dxfeed-graal-net-api/assets/12551442/6445e168-12c9-44c6-8543-40bc7abab85f)

Is Blazor WASM supported?

**Comment by stdcion** [comment]
Hi @voros1!

Apologies for the late reply. This library is built as a language-specific wrapper over the [dxFeed Graal Native](https://dxfeed.jfrog.io/artifactory/maven-open/com/dxfeed/graal-native-api/) library, which was compiled with [GraalVM Native Image](https://www.graalvm.org/latest/reference-manual/native-image/). This gives us a lot of advantages in API development, but also imposes some limitations.
Unfortunately, GraalVM Native Image does not have WASM support at the moment. You can track the corresponding [issue](https://github.com/oracle/graal/issues/3391) in the oracle repository. Now we have builds for `win-x64,` `linux-x64`, `osx-x64` and `osx-arm64` (Apple Silicon). We plan to add a build for WASM when this is ready in [GraalVM Native Image](https://www.graalvm.org/latest/reference-manual/native-image/). I also want to mention that you can use [Blazor Server](https://learn.microsoft.com/en-us/aspnet/core/blazor/?WT.mc_id=dotnet-35129-website&view=aspnetcore-7.0#blazor-server) instead of [Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/?WT.mc_id=dotnet-35129-website&view=aspnetcore-7.0#blazor-webassembly), in this case the loading of the native libraries should be done correctly..

Best regards,
dxFeed APIs Team
